import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { type Options, compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, "..");
const repoRoot = join(pkgRoot, "../..");
const generatedDir = join(pkgRoot, "src/generated");

const BANNER = `/**
 * Generated by \`pnpm gen\` from schema/*. Do not edit.
 * Source of truth: schema/enspack.schema.json and schema/enspack.lock.schema.json.
 */

`;

const COMPILE_OPTS: Partial<Options> = {
  bannerComment: "",
  additionalProperties: false,
  unknownAny: true,
  unreachableDefinitions: false,
  cwd: join(repoRoot, "schema"),
  style: {
    printWidth: 100,
    semi: true,
    singleQuote: false,
    trailingComma: "all",
  },
};

async function compileSchema(relPath: string, title: string, name: string): Promise<string> {
  const raw = JSON.parse(await readFile(join(repoRoot, relPath), "utf8")) as Record<
    string,
    unknown
  >;
  raw.title = title;
  const body = await compile(raw, name, COMPILE_OPTS);
  return BANNER + body;
}

/** Render Manifest types from schema/enspack.schema.json. */
export async function renderManifestTypes(): Promise<string> {
  return compileSchema("schema/enspack.schema.json", "Manifest", "Manifest");
}

/** Render Lockfile types from schema/enspack.lock.schema.json. */
export async function renderLockfileTypes(): Promise<string> {
  return compileSchema("schema/enspack.lock.schema.json", "Lockfile", "Lockfile");
}

/** Write src/generated/{manifest,lockfile}.ts from the repo schemas. */
export async function writeGenerated(): Promise<void> {
  await mkdir(generatedDir, { recursive: true });
  await writeFile(join(generatedDir, "manifest.ts"), await renderManifestTypes());
  await writeFile(join(generatedDir, "lockfile.ts"), await renderLockfileTypes());
}

const invoked = process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1];
if (invoked) {
  await writeGenerated();
  process.stderr.write("wrote src/generated/manifest.ts and src/generated/lockfile.ts\n");
}
