/** ENSv2 EAC: admin variant of a role is `role << 128` (issue #17). */
export function adminOf(role: bigint): bigint {
  return role << 128n;
}

/** ENSv2 EAC root resource id (issue #17). */
export const ROOT_RESOURCE = 0n;

const REGISTRAR = 1n << 0n;
const REGISTER_RESERVED = 1n << 4n;
const SET_PARENT = 1n << 8n;
const UNREGISTER = 1n << 12n;
const RENEW = 1n << 16n;
const SET_SUBREGISTRY = 1n << 20n;
const SET_RESOLVER = 1n << 24n;
const CAN_TRANSFER = 1n << 28n;
const SET_URI = 1n << 36n;
const REGISTRY_UPGRADE = 1n << 124n;

/** ENSv2 PermissionedRegistry roles (issue #17). */
export const REGISTRY_ROLES = {
  REGISTRAR,
  REGISTRAR_ADMIN: adminOf(REGISTRAR),
  REGISTER_RESERVED,
  REGISTER_RESERVED_ADMIN: adminOf(REGISTER_RESERVED),
  SET_PARENT,
  SET_PARENT_ADMIN: adminOf(SET_PARENT),
  UNREGISTER,
  UNREGISTER_ADMIN: adminOf(UNREGISTER),
  RENEW,
  RENEW_ADMIN: adminOf(RENEW),
  SET_SUBREGISTRY,
  SET_SUBREGISTRY_ADMIN: adminOf(SET_SUBREGISTRY),
  SET_RESOLVER,
  SET_RESOLVER_ADMIN: adminOf(SET_RESOLVER),
  CAN_TRANSFER_ADMIN: adminOf(CAN_TRANSFER),
  SET_URI,
  SET_URI_ADMIN: adminOf(SET_URI),
  UPGRADE: REGISTRY_UPGRADE,
  UPGRADE_ADMIN: adminOf(REGISTRY_UPGRADE),
} as const;

const SET_ADDR = 1n << 0n;
const SET_TEXT = 1n << 4n;
const SET_CONTENTHASH = 1n << 8n;
const SET_PUBKEY = 1n << 12n;
const SET_ABI = 1n << 16n;
const SET_INTERFACE = 1n << 20n;
const SET_NAME = 1n << 24n;
const SET_ALIAS = 1n << 28n;
const CLEAR = 1n << 32n;
const SET_DATA = 1n << 36n;
const RESOLVER_UPGRADE = 1n << 124n;

/** ENSv2 PermissionedResolver roles (issue #17). */
export const RESOLVER_ROLES = {
  SET_ADDR,
  SET_ADDR_ADMIN: adminOf(SET_ADDR),
  SET_TEXT,
  SET_TEXT_ADMIN: adminOf(SET_TEXT),
  SET_CONTENTHASH,
  SET_CONTENTHASH_ADMIN: adminOf(SET_CONTENTHASH),
  SET_PUBKEY,
  SET_PUBKEY_ADMIN: adminOf(SET_PUBKEY),
  SET_ABI,
  SET_ABI_ADMIN: adminOf(SET_ABI),
  SET_INTERFACE,
  SET_INTERFACE_ADMIN: adminOf(SET_INTERFACE),
  SET_NAME,
  SET_NAME_ADMIN: adminOf(SET_NAME),
  SET_ALIAS,
  SET_ALIAS_ADMIN: adminOf(SET_ALIAS),
  CLEAR,
  CLEAR_ADMIN: adminOf(CLEAR),
  SET_DATA,
  SET_DATA_ADMIN: adminOf(SET_DATA),
  UPGRADE: RESOLVER_UPGRADE,
  UPGRADE_ADMIN: adminOf(RESOLVER_UPGRADE),
} as const;

/** Roles ETHRegistrar grants a new .eth name owner (issue #17). */
export const NAME_OWNER_ROLES =
  REGISTRY_ROLES.SET_SUBREGISTRY |
  REGISTRY_ROLES.SET_SUBREGISTRY_ADMIN |
  REGISTRY_ROLES.SET_RESOLVER |
  REGISTRY_ROLES.SET_RESOLVER_ADMIN |
  REGISTRY_ROLES.CAN_TRANSFER_ADMIN;

/** Root roles granted when deploying a UserRegistry proxy (issue #17). */
export const USER_REGISTRY_ROOT_ROLES =
  REGISTRY_ROLES.REGISTRAR |
  REGISTRY_ROLES.REGISTRAR_ADMIN |
  REGISTRY_ROLES.RENEW |
  REGISTRY_ROLES.RENEW_ADMIN |
  REGISTRY_ROLES.SET_PARENT |
  REGISTRY_ROLES.SET_PARENT_ADMIN |
  REGISTRY_ROLES.SET_SUBREGISTRY |
  REGISTRY_ROLES.SET_SUBREGISTRY_ADMIN |
  REGISTRY_ROLES.SET_RESOLVER |
  REGISTRY_ROLES.SET_RESOLVER_ADMIN |
  REGISTRY_ROLES.UPGRADE |
  REGISTRY_ROLES.UPGRADE_ADMIN;

/** Root roles granted when deploying a PermissionedResolver proxy (issue #17). */
export const RESOLVER_ADMIN_ROLES =
  RESOLVER_ROLES.SET_TEXT |
  RESOLVER_ROLES.SET_TEXT_ADMIN |
  RESOLVER_ROLES.SET_CONTENTHASH |
  RESOLVER_ROLES.SET_CONTENTHASH_ADMIN |
  RESOLVER_ROLES.SET_ADDR |
  RESOLVER_ROLES.SET_ADDR_ADMIN |
  RESOLVER_ROLES.UPGRADE |
  RESOLVER_ROLES.UPGRADE_ADMIN;
