import { describe, expect, it } from "vitest";
import {
  NAME_OWNER_ROLES,
  REGISTRY_ROLES,
  RESOLVER_ADMIN_ROLES,
  RESOLVER_ROLES,
  ROOT_RESOURCE,
  USER_REGISTRY_ROOT_ROLES,
  adminOf,
} from "../../src/index.js";

describe("ENSv2 role helpers", () => {
  it("adminOf shifts 128 bits", () => {
    expect(adminOf(REGISTRY_ROLES.REGISTRAR)).toBe(REGISTRY_ROLES.REGISTRAR_ADMIN);
    expect(adminOf(1n << 28n)).toBe(REGISTRY_ROLES.CAN_TRANSFER_ADMIN);
    expect(adminOf(RESOLVER_ROLES.SET_TEXT)).toBe(RESOLVER_ROLES.SET_TEXT_ADMIN);
  });

  it("ROOT_RESOURCE is 0", () => {
    expect(ROOT_RESOURCE).toBe(0n);
  });

  it("NAME_OWNER_ROLES matches ETHRegistrar grant bitmap", () => {
    expect(NAME_OWNER_ROLES).toBe(
      REGISTRY_ROLES.SET_SUBREGISTRY |
        REGISTRY_ROLES.SET_SUBREGISTRY_ADMIN |
        REGISTRY_ROLES.SET_RESOLVER |
        REGISTRY_ROLES.SET_RESOLVER_ADMIN |
        REGISTRY_ROLES.CAN_TRANSFER_ADMIN,
    );
  });

  it("USER_REGISTRY_ROOT_ROLES includes registrar, renew, parent, subregistry, resolver, upgrade", () => {
    expect(USER_REGISTRY_ROOT_ROLES & REGISTRY_ROLES.REGISTRAR).toBe(REGISTRY_ROLES.REGISTRAR);
    expect(USER_REGISTRY_ROOT_ROLES & REGISTRY_ROLES.REGISTRAR_ADMIN).toBe(
      REGISTRY_ROLES.REGISTRAR_ADMIN,
    );
    expect(USER_REGISTRY_ROOT_ROLES & REGISTRY_ROLES.RENEW).toBe(REGISTRY_ROLES.RENEW);
    expect(USER_REGISTRY_ROOT_ROLES & REGISTRY_ROLES.SET_PARENT).toBe(REGISTRY_ROLES.SET_PARENT);
    expect(USER_REGISTRY_ROOT_ROLES & REGISTRY_ROLES.UPGRADE_ADMIN).toBe(REGISTRY_ROLES.UPGRADE_ADMIN);
  });

  it("RESOLVER_ADMIN_ROLES includes text, contenthash, addr, upgrade", () => {
    expect(RESOLVER_ADMIN_ROLES & RESOLVER_ROLES.SET_TEXT).toBe(RESOLVER_ROLES.SET_TEXT);
    expect(RESOLVER_ADMIN_ROLES & RESOLVER_ROLES.SET_CONTENTHASH_ADMIN).toBe(
      RESOLVER_ROLES.SET_CONTENTHASH_ADMIN,
    );
    expect(RESOLVER_ADMIN_ROLES & RESOLVER_ROLES.SET_ADDR).toBe(RESOLVER_ROLES.SET_ADDR);
    expect(RESOLVER_ADMIN_ROLES & RESOLVER_ROLES.UPGRADE).toBe(RESOLVER_ROLES.UPGRADE);
  });
});
